@echo off
set PYTHONIOENCODING=utf-8
echo Seeding districts...
call .\venv\Scripts\python.exe scripts\seed_districts.py
echo Seeding climate history...
call .\venv\Scripts\python.exe scripts\seed_climate_history.py
echo Seeding malaria history...
call .\venv\Scripts\python.exe scripts\seed_malaria_history.py
echo Computing baselines...
call .\venv\Scripts\python.exe scripts\compute_baselines.py
echo Backfilling predictions...
call .\venv\Scripts\python.exe scripts\backfill_predictions.py
echo All seeding completed!
